name: eduvise
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.8
  onboarding: ^3.1.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  get: ^4.6.1           
  get_storage: ^2.0.3  
  flutter_otp_text_field: ^1.1.1
  form_validator: ^2.1.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  flutter_spinkit: ^5.1.0
  http: ^1.0.0
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.13.2

flutter_native_splash:
  color: "#088395"
  image: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#088395"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
   - assets/images/